services:

  php-8.2:
    build:
      args:
        PHP_VERSION: 8.2
      context: .
    working_dir: /app
    environment:
      WORKDIR: ./cluster/8.2
      LOGGING: yes
    volumes:
      - ./:/app

  php-8.1:
    build:
      args:
        PHP_VERSION: 8.1
      context: .
    working_dir: /app
    environment:
      WORKDIR: ./cluster/8.1
      LOGGING: yes
    volumes:
      - ./:/app

  php-8.0:
    build:
      args:
        PHP_VERSION: 8.0
      context: .
    working_dir: /app
    environment:
      WORKDIR: ./cluster/8.0
      LOGGING: yes
    volumes:
      - ./:/app
