name: run-tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2]
        dependency-version: [prefer-lowest, prefer-stable]
        framework: [laravel, lumen]
        laravel-version: ["6.*", "7.*", "8.*", "9.*", "10.*"]
        horizon: [0, 1]
        exclude:
          # lumen doesn't support horizon
          - framework: lumen
            horizon: 1
          # horizon for laravel 6/7 does not support PHP 8+
          - laravel-version: "6.*"
            horizon: 1
          - laravel-version: "7.*"
            horizon: 1
          # Lumen 6/7 does not support PHP >=8.0
          - framework: lumen
            laravel-version: "6.*"
          - framework: lumen
            laravel-version: "7.*"
          # Laravel 6 does not support PHP >=8.1
          - laravel-version: "6.*"
            php: 8.1
          - laravel-version: "6.*"
            php: 8.2
          # Laravel 7 does not support PHP >=8.1
          - laravel-version: "7.*"
            php: 8.1
          - laravel-version: "7.*"
            php: 8.2
          # Laravel 8 does not support PHP >=8.2
          - laravel-version: "8.*"
            php: 8.2
          # Laravel 10 does not support PHP <=8.0
          - laravel-version: "10.*"
            php: 8.0

    name: PHP (${{ matrix.php }}) - ${{ matrix.framework }} ${{ matrix.laravel-version }} - Horizon (${{ matrix.horizon }}) - Composer (${{ matrix.dependency-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: shogo82148/actions-setup-redis@v1
        with:
          auto-start: "false"

      - name: Start up cluster
        run: SUPERVISE=no ./start-cluster.sh || { cat ./cluster/*.log; false; }

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip
          coverage: none

      - name: Setup dependencies
        run: ./scripts/setup-dependencies.sh "${{ matrix.framework }}" "${{ matrix.laravel-version }}" "${{ matrix.horizon }}" "--${{ matrix.dependency-version }}"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json";
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json";

      - name: Execute tests
        run: ./scripts/phpunit.sh "${{ matrix.framework }}" "${{ matrix.laravel-version }}" "${{ matrix.horizon }}"
