name: run-tests-5.5

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.0, 7.1, 7.2, 7.3]
        dependency-version: [prefer-lowest, prefer-stable]
        framework: [laravel, lumen]
        laravel-version: ["5.5.*"]
        horizon: [0, 1]
        exclude:
          # lumen doesn't support horizon
          - framework: lumen
            horizon: 0

    name: PHP (${{ matrix.php }}) - Framework (${{ matrix.framework }}) - Horizon (${{ matrix.horizon }}) - Composer (${{ matrix.dependency-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip
          coverage: none

      - uses: shogo82148/actions-setup-redis@v1
        with:
          auto-start: "false"

      - name: Setup dependencies
        run: |
          if [ "${{ matrix.framework }}" == "laravel" ]; then
              composer remove --dev --no-update "laravel/lumen-framework"
              composer require --dev --no-update "laravel/laravel-framework:${{ matrix.laravel-version }}"
          elif [ "${{ matrix.framework }}" == "lumen" ]; then
              composer remove --dev --no-update "laravel/laravel-framework"
              composer require --dev --no-update "laravel/lumen-framework:${{ matrix.laravel-version }}"
          fi

          if [ "${{ matrix.horizon }}" == "0" ]; then
              composer remove --dev --no-update "laravel/horizon"
          fi

          cat composer.json

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Start up cluster
        run: SUPERVISE=no ./start-cluster.sh || { cat ./cluster/*.log; false; }

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json";
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json";

      - name: Execute tests
        run: |
          EXCLUDED_GROUPS=()

          if [ "${{ matrix.framework }}" == "lumen" ]; then
              EXCLUDED_GROUPS+=(laravel)
          fi

          if [ "${{ matrix.horizon }}" == "0" ]; then
              EXCLUDED_GROUPS+=(horizon)
          fi

          EXCLUDE_GROUPS="--exclude-group $(IFS=","; echo ${EXCLUDED_GROUPS[*]})"
          if [ "${EXCLUDE_GROUPS}" == "--exclude-group " ]; then
              EXCLUDE_GROUP=''
          fi

          vendor/bin/phpunit ${EXCLUDE_GROUP}
