name: run-tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2]
        dependency-version: [prefer-lowest, prefer-stable]
        framework: [laravel, lumen]
        laravel-version: ["6.*", "7.*", "8.*", "9.*", 10.*"]
        horizon: [0, 1]
        exclude:
          # lumen doesn't support horizon
          - framework: lumen
            horizon: 0
          - laravel-version: "6.*"
            php: 8.1
          - laravel-version: "6.*"
            php: 8.2
          - laravel-version: "7.*"
            php: 8.1
          - laravel-version: "7.*"
            php: 8.2
          - laravel-version: "8.*"
            php: 8.2

    name: PHP (${{ matrix.php }}) - ${{ matrix.framework }} ${{ matrix.laravel-version }} - Horizon (${{ matrix.horizon }}) - Composer (${{ matrix.dependency-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip
          coverage: none

      - uses: shogo82148/actions-setup-redis@v1
        with:
          auto-start: "false"

      - name: Install dependencies
        run: ./scripts/install-dependencies.sh "${{ matrix.framework }}" "${{ matrix.laravel-version }}" "${{ matrix.horizon }}"

      - name: Start up cluster
        run: SUPERVISE=no ./start-cluster.sh || { cat ./cluster/*.log; false; }

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json";
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json";

      - name: Execute tests
        run: |
          EXCLUDED_GROUPS=()

          if [ "${{ matrix.framework }}" == "lumen" ]; then
              EXCLUDED_GROUPS+=(laravel)
          fi

          if [ "${{ matrix.horizon }}" == "0" ]; then
              EXCLUDED_GROUPS+=(horizon)
          fi

          EXCLUDE_GROUP_SWITCH="--exclude-group $(IFS=","; echo ${EXCLUDED_GROUPS[*]})"
          if [ "${EXCLUDE_GROUP_SWITCH}" == "--exclude-group " ]; then
              EXCLUDE_GROUP_SWITCH=''
          fi

          vendor/bin/phpunit ${EXCLUDE_GROUP_SWITCH}
