name: run-tests

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [5.6, 7.0, 7.1, 7.2, 7.3 7.4, 8.0, 8.1, 8.2]
                dependency-version: [prefer-lowest, prefer-stable]
                framework: [laravel, lumen]
                laravel-version: [">=5.4.0 <5.4.20", ">=5.4.20 <5.5.0", "5.5.*", "5.6.*", "5.7.*", "5.8.*", "6.*", "7.*", "8.*", "9.*", "10.*"]
                horizon: [0, 1]
                exclude:
                  # lumen doesn't support horizon
                  - framework: lumen
                    horizon: 0

                  # laravel 5.4 supports php 5.6 ~ 7.3
                  - laravel-version: ">=5.4.0 <5.4.20"
                    php: 7.4
                  - laravel-version: ">=5.4.0 <5.4.20"
                    php: 8.0
                  - laravel-version: ">=5.4.0 <5.4.20"
                    php: 8.1
                  - laravel-version: ">=5.4.0 <5.4.20"
                    php: 8.2

                  - laravel-version: ">=5.4.20 <5.5.0"
                    php: 7.4
                  - laravel-version: ">=5.4.20 <5.5.0"
                    php: 8.0
                  - laravel-version: ">=5.4.20 <5.5.0"
                    php: 8.1
                  - laravel-version: ">=5.4.20 <5.5.0"
                    php: 8.2

                  # laravel 5.5 supports php 5.6 ~ 7.3
                  - laravel-version: "5.5.*"
                    php: 7.4
                  - laravel-version: "5.5.*"
                    php: 8.0
                  - laravel-version: "5.5.*"
                    php: 8.1
                  - laravel-version: "5.5.*"
                    php: 8.2

                  # laravel 5.6 supports php 7.1 ~ 7.3
                  - laravel-version: "5.6.*"
                    php: 5.6
                  - laravel-version: "5.6.*"
                    php: 7.0
                  - laravel-version: "5.6.*"
                    php: 7.4
                  - laravel-version: "5.6.*"
                    php: 8.0
                  - laravel-version: "5.6.*"
                    php: 8.1
                  - laravel-version: "5.6.*"
                    php: 8.2

                  # laravel 5.7 supports php 7.1 ~ 7.3
                  - laravel-version: "5.7.*"
                    php: 5.6
                  - laravel-version: "5.7.*"
                    php: 7.0
                  - laravel-version: "5.7.*"
                    php: 7.4
                  - laravel-version: "5.7.*"
                    php: 8.0
                  - laravel-version: "5.7.*"
                    php: 8.1
                  - laravel-version: "5.7.*"
                    php: 8.2

                  # laravel 5.8 supports php 7.1 ~ 7.3
                  - laravel-version: "5.8.*"
                    php: 5.6
                  - laravel-version: "5.8.*"
                    php: 7.0
                  - laravel-version: "5.8.*"
                    php: 7.4
                  - laravel-version: "5.8.*"
                    php: 8.0
                  - laravel-version: "5.8.*"
                    php: 8.1
                  - laravel-version: "5.8.*"
                    php: 8.2

                  # laravel 6.x supports php 7.2 ~ 8.0
                  - laravel-version: "6.*"
                    php: 5.6
                  - laravel-version: "6.*"
                    php: 7.0
                  - laravel-version: "6.*"
                    php: 7.1
                  - laravel-version: "6.*"
                    php: 7.4
                  - laravel-version: "6.*"
                    php: 8.1
                  - laravel-version: "6.*"
                    php: 8.2

                  # laravel 7.x supports php 7.2 ~ 8.0
                  - laravel-version: "7.*"
                    php: 5.6
                  - laravel-version: "7.*"
                    php: 7.0
                  - laravel-version: "7.*"
                    php: 7.1
                  - laravel-version: "7.*"
                    php: 7.4
                  - laravel-version: "7.*"
                    php: 8.1
                  - laravel-version: "7.*"
                    php: 8.2

                  # laravel 8.x supports php 7.3 ~ 8.1
                  - laravel-version: "8.*"
                    php: 5.6
                  - laravel-version: "8.*"
                    php: 7.0
                  - laravel-version: "8.*"
                    php: 7.1
                  - laravel-version: "8.*"
                    php: 7.2
                  - laravel-version: "8.*"
                    php: 8.2

                  # laravel 9.x supports php 8.0 ~ 8.2
                  - laravel-version: "8.*"
                    php: 5.6
                  - laravel-version: "8.*"
                    php: 7.0
                  - laravel-version: "8.*"
                    php: 7.1
                  - laravel-version: "8.*"
                    php: 7.2
                  - laravel-version: "8.*"
                    php: 7.3
                  - laravel-version: "8.*"
                    php: 7.4

                  # laravel 10.x supports php 8.1 ~ 8.2
                  - laravel-version: "8.*"
                    php: 5.6
                  - laravel-version: "8.*"
                    php: 7.0
                  - laravel-version: "8.*"
                    php: 7.1
                  - laravel-version: "8.*"
                    php: 7.2
                  - laravel-version: "8.*"
                    php: 7.3
                  - laravel-version: "8.*"
                    php: 7.4
                  - laravel-version: "8.*"
                    php: 8.0

        name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: zip
                    coverage: none

            -   name: Setup dependencies
                run: |
                    if [ "${{ matrix.framework }}" == "laravel" ]; then
                        composer remove --dev --no-update "laravel/lumen-framework"
                        composer require --dev --no-update "laravel/laravel-framework:${{ matrix.laravel-version }}"
                    else if [ "${{ matrix.framework }}" == "lumen" ]; then
                        composer remove --dev --no-update "laravel/laravel-framework"
                        composer require --dev --no-update "laravel/lumen-framework:${{ matrix.laravel-version }}"
                    fi

                    if [ "${{ matrix.horizon }}" == "0" ]; then
                        composer remove --dev --no-update "laravel/horizon"
                    fi

            -   name: Install dependencies
                run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            -   name: Start up cluster
                run: ./start-cluster.sh || { cat /.cluser/*.log; false; }

            -   name: Setup Problem Matches
                run: |
                    echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                    echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: Execute tests
                run: |
                    EXCLUDE_GROUPS="+laravel-only,-horizon"

                    if [ "${{ matrix.framework }}" == "lumen" ]; then
                        EXCLUDE_GROUPS="-horizon"
                    fi

                    if [ "${{ matrix.horizon }}" == "1" ]; then
                        EXCLUDE_GROUPS=""
                    fi

                    vendor/bin/phpunit --exclude-group ${EXCLUDE_GROUPS}
