name: run-tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2]
        dependency-version: [prefer-lowest, prefer-stable]
        framework: [laravel, lumen]
        laravel-version: ["6.*", "7.*", "8.*", "9.*", "10.*"]
        horizon: [0, 1]
        exclude:
          # lumen doesn't support horizon
          - framework: lumen
            horizon: 1
          - framework: lumen
            laravel-version: "6.*"
          - laravel-version: "6.*"
            php: 8.1
          - laravel-version: "6.*"
            php: 8.2
          - laravel-version: "7.*"
            php: 8.1
          - laravel-version: "7.*"
            php: 8.2
          - laravel-version: "8.*"
            php: 8.2
          - laravel-version: "10.*"
            php: 8.0

    name: PHP (${{ matrix.php }}) - ${{ matrix.framework }} ${{ matrix.laravel-version }} - Horizon (${{ matrix.horizon }}) - Composer (${{ matrix.dependency-version }})

    services:
      redis:
        image: bitnami/redis:6.2.4-debian-10-r35
        ports:
          - 6379:6379
        env:
          ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd "redis-cli -p 6379 ping"
          --health-start-period 5s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis-sentinel:
        image: bitnami/redis-sentinel:6.2.4-debian-10-r39
        ports:
          - 26379:26379
        env:
          REDIS_MASTER_HOST: redis
          REDIS_MASTER_SET: service1
          REDIS_SENTINEL_QUORUM: 1
        options: >-
          --health-cmd "redis-cli -p 26379 ping"
          --health-start-period 5s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip
          coverage: none

      - name: Setup dependencies
        run: ./scripts/setup-dependencies.sh "${{ matrix.framework }}" "${{ matrix.laravel-version }}" "${{ matrix.horizon }}" "--${{ matrix.dependency-version }}"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json";
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json";

      - name: Execute tests
        run: ./scripts/phpunit.sh "${{ matrix.framework }}" "${{ matrix.laravel-version }}" "${{ matrix.horizon }}"
        env:
          TEST_REDIS_SENTINEL_HOST: "127.0.0.1:26379"

